const USERS_TYPES = {
  USERS_FETCH_REQUEST: '@@USERS/USERS_FETCH_REQUEST',
  USERS_FETCH_SUCCESS: '@@USERS/USERS_FETCH_SUCCESS',
  USERS_FETCH_FAILURE: '@@USERS/USERS_FETCH_FAILURE',
};

export default USERS_TYPES;